apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotsim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotsim-app
  template:
    metadata:
      labels:
        app: iotsim-app
        version: v1
    spec:
      containers:
      - name: iotsim-app
        image: gunter04/iotsim-multiple:latest
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /code/config
          name: iotsim-config-configmap  
        - mountPath: /code/certificates
          name: iotsim-certs-configmap  
      volumes:
      - name: iotsim-config-configmap
        configMap: 
          name: iotsim-configfile
      - name: iotsim-certs-configmap
        configMap: 
          name: iotsim-certsfile   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iotsim-configfile
data:
  iotsim.cfg: |
    # This file contains the simulator configuration settings
    [server]
    mqttServerUrl = a4042ecf-281e-4d4a-b721-c9b43461e188.eu10.cp.iot.sap
    mqttServerPort = 8883
    pemCertFilePath = ./certificates/

    [topics]
    ackTopicLevel = ack/
    measuresTopicLevel = measures/

    [messages]
    messageTemplate = {{ "capabilityAlternateId": "TEAM{iotDevice.teamno}_CAPABAILITY", "sensorAlternateId": "team{iotDevice.teamno}_sensor", "measures": [{{"temperature": "{random.randint(10,50)}"}}] }}

    [timing]
    pauseInSeconds = 20 # Time until the next message is sent
    runtimeOfProgram = 1 # Time until the program stops sending (0 = Never) in minutes
